title: Florian's Blog
description: Exploring Clifford Quantum Cellular Automata and Quantum Computing
author: Florian Richter
email: florian2richter@example.com  # Replace with your actual email
baseurl: ""
url: "https://florian2richter.github.io"

# Social media
github_username: Florian2Richter

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  categories:
    output: true
    permalink: /category/:path/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      mathjax: true 